---
- name: Converge
  hosts: all
  vars:
    - nagios-remote-plugin-executor_deployment_users_home: /home/vagrant
    - nagios-remote-plugin-executor_testing_provider: vagrant
  roles:
    - nagios-remote-plugin-executor