---
# file: project/nagios-remote-plugin-executor.yml

- hosts: nagios-remote-plugin-executor
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/nagios-remote-plugin-executor"
    - debug: var=fact_role_path

  roles:

    - nagios-remote-plugin-executor
